### ISSUE TITLE
maybe forget include one file

### ISSUE THREAD

**Issue by huguangju** [SixArm/sixarm_git_gitconfig#5]
if not include 
``` path = sixarm_git_gitconfig/gitconfig.d/alias.txt; ```, alias  ineffective.

> why not add it in sixarm_git_gitconfig/gitconfig file?

**Comment by joelparkerhenderson** [comment]
You're correct. Thank you. I am fixing it right now.

**Comment by joelparkerhenderson** [comment]
Fixed. Can you try it now and see if that solves it for you? Thank you.

**Comment by huguangju** [comment]
Thank you.
