### ISSUE TITLE
how to use "git e"?

### ISSUE THREAD

**Issue by huguangju** [SixArm/sixarm_git_gitconfig#6]
```shell
# edit - pipe the diff output to your editor of choice.
  e = !"git diff | $EDITOR"
```

**Comment by joelparkerhenderson** [comment]
That's a poor alias; I'll delete it now. 

(The goal is to be able to diff the repo, and pipe the results into your currently-configured editor. However, some of the most popular editors do not allow piping stdin directly to the editor. For example, the `vim` editor command would need a dash that indicates stdin, and the `emacs` editor uses stdin for something completely different.)

**Comment by huguangju** [comment]
Thank you very much for your detailed explanation.
